mysite/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('category/<int:category_id>', views.category_list, name='category_list'),
    path('article/<int:article_id>', views.article_detail, name='article_detail'),
    path('search/', views.search, name='search'),
    path('archives/<int:year>/<int:month>/', views.archives, name='archives'),
    path('add_article/', views.add_article, name='add_article'),
    path('published_articles/', views.published_articles, name='published_articles'),
    path('edit_article/<int:article_id>/', views.edit_article, name='edit_article'),
    path('drafts/', views.draft_list, name='draft_list'),
    path('delete_article/<int:article_id>', views.delete_article, name='delete_article'),
    path('delete_comment/<int:comment_id>', views.delete_comment, name='delete_comment'),
    path('comment_list/', views.comment_list, name='comment_list'),
    path('get_comment_replies/<int:comment_id>/', views.get_comment_replies, name='get_comment_replies'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from utils.upload import upload_file
urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('blog.urls')),
    path('uploads/', upload_file, name='uploads')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/users/urls.py
# users/views.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('register/', views.register, name='register'),
    path('active/<active_code>', views.active_user, name='active_user'),
    path('forget_pwd/', views.forget_pwd, name='forget_pwd'),
    path('forget_pwd_url/<active_code>', views.forget_pwd_url, name='forget_pwd_url'),
    path('user_profile/', views.user_profile, name='user_profile'),
    path('logout/', views.logout_view, name='logout'),
    path('edit/', views.edit_users, name='edit'),
    path('activate_account/', views.register, name='activate_account'),
    path('invalid_link/', views.active_user, name='invalid_link'),
    path('pending_activation/', views.register, name='pending_activation'),
    path('message_profile/', views.message_profile, name='message_profile'),
    path('follow/<str:username>/', views.follow_unfollow, name='follow_unfollow'),
    path('<str:username>/followers/', views.followers, name='followers_list'),
    path('other_user_profile/<str:username>/', views.other_user_profile, name='other_user_profile'),
    path('my_followers/', views.my_followers, name='my_followers'),  # 当前用户的粉丝列表
]

mysite/blog/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Article, Tag, Comment


class AddForm(forms.ModelForm):
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Article
        fields = ('title', 'description', 'content', 'category', 'tags',)  # 不包括 tags 和 owner


class ArticleForm(forms.ModelForm):
    # 处理标签，使用多选字段，并显示为复选框
    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),  # 获取所有标签
        widget=forms.CheckboxSelectMultiple,  # 使用复选框来选择多个标签
        required=False  # 标签为非必填项
    )

    class Meta:
        model = Article
        # 定义需要的字段
        fields = ['title', 'description', 'content', 'category', 'tags']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'input', 'placeholder': 'Enter the title'}),
            'description': forms.Textarea(attrs={'class': 'textarea', 'placeholder': 'Enter the description'}),
            'content': forms.Textarea(attrs={'class': 'textarea', 'placeholder': 'Enter the content'}),
            'category': forms.Select(attrs={'class': 'select'}),
        }

    # 你可以选择性地添加自定义的验证逻辑
    def clean_title(self):
        title = self.cleaned_data.get('title')
        if not title:
            raise ValidationError('Title cannot be empty.')
        return title

    def clean_content(self):
        content = self.cleaned_data.get('content')
        return content


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={'class': 'textarea', 'rows': 1, 'placeholder': 'Add a comment...'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # 如果 content 字段的值为 None，将其初始化为空字符串
        self.fields['content'].initial = self.fields['content'].initial or ''

mysite/blog/views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.contrib import messages
from .models import Category, Article, Tag, Comment
from django.db.models import Q, F
from datetime import datetime
from django.core.paginator import Paginator
from django.contrib.auth.models import User
from .forms import AddForm, ArticleForm, CommentForm


def index(request):
    article_list = Article.objects.filter(is_draft=False).order_by('-add_date')
    paginator = Paginator(article_list, 6)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj': page_obj}
    return render(request, 'blog/index.html', context)


def category_list(request, category_id):
    category = get_object_or_404(Category, id=category_id)
    articles = category.article_set.all()
    paginator = Paginator(articles, 2)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'category': category, 'page_obj': page_obj}
    return render(request, 'blog/list.html', context)


def article_detail(request, article_id):
    article = get_object_or_404(Article, id=article_id)

    # 获取顶级评论并预取每个评论的回复
    comments = article.comments.filter(parent__isnull=True).prefetch_related('replies').order_by('add_date')

    # ordered by article id
    prev_article = Article.objects.filter(id__lt=article_id).last()
    next_article = Article.objects.filter(id__gt=article_id).first()

    if request.method == 'POST':
        if request.user.is_authenticated:
            form = CommentForm(request.POST)
            if form.is_valid():
                comment = form.save(commit=False)
                comment.article = article
                comment.user = request.user
                # 检查是否为回复
                parent_id = request.POST.get('parent_id')
                if parent_id:
                    parent_comment = Comment.objects.get(id=parent_id)
                    comment.parent = parent_comment
                comment.save()
                return redirect('blog:article_detail', article_id=article.id)
        else:
            messages.info(request, "Please log in to comment.")
            return redirect(request.path)  # 假设你的登录视图的 URL 名为 'login'
    else:
        form = CommentForm()

    # print(article.views)
    Article.objects.filter(id=article_id).update(views=F('views') + 1)  # not recommended
    context = {
               'article': article,
               'prev_article': prev_article,
               'next_article': next_article,
               'comments': comments,
               'form': form,
               }
    return render(request, 'blog/detail.html', context)


def search(request):
    keyword = request.GET.get('keyword')

    if not keyword:
        article_list = Article.objects.all()
    else:
        article_list = Article.objects.filter(Q(title__icontains=keyword) | Q(title__icontains=keyword) | Q(content__icontains=keyword))
    paginator = Paginator(article_list, 2)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj
    }
    return render(request, 'blog/index.html', context)


def archives(request, year, month):
    article_list = Article.objects.filter(add_date__year=year, add_date__month=month)
    paginator = Paginator(article_list, 2)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    month_name = datetime(year=int(year), month=int(month), day=1).strftime('%B')
    context = {'page_obj': page_obj, 'article_list': article_list, 'year': year, 'month': month_name}
    return render(request, 'blog/archives_list.html', context)


@login_required(login_url='users:login')
def add_article(request):
    if request.method == "POST":
        form = AddForm(request.POST, request.FILES)
        if form.is_valid():
            new_article = form.save(commit=False)
            new_article.owner = request.user
            # print(request.POST)

            # 判断用户点击了哪个按钮
            if 'publish' in request.POST:
                new_article.is_draft = False
            elif 'save_as_draft' in request.POST:
                new_article.is_draft = True

            # 保存文章实例到数据库
            new_article.save()

            # 处理用户选择的标签
            tags = form.cleaned_data.get('tags')
            if tags:
                # 由于文章已保存，now we can set tags safely
                new_article.tags.set(tags)
                new_article.save()

            # 如果是草稿，则将草稿保存到 session
            if new_article.is_draft:
                request.session['draft_article'] = {
                    'title': new_article.title,
                    'description': new_article.description,
                    'content': new_article.content,
                    'tags': [tag.name for tag in new_article.tags.all()],
                    'category': new_article.category.id
                }
                # 使用 reverse 函数获取 URL
                redirect_url = reverse('blog:draft_list')
            else:
                redirect_url = reverse('blog:index')
            return JsonResponse({'success': True, 'redirect': redirect_url})

        else:
            # Return form errors as JSON
            return JsonResponse({'success': False, 'errors': form.errors}, status=400)
    else:
        form = AddForm()

    return render(request, 'users/add_article.html', {'add_form': form})


@login_required(login_url='users:login')
def edit_article(request, article_id):
    article = get_object_or_404(Article, id=article_id, owner=request.user)

    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES, instance=article)
        if form.is_valid():
            form.save()  # Save the updated article
            return JsonResponse({'success': True, 'redirect': reverse('blog:index')})
        else:
            return JsonResponse({'success': False, 'errors': form.errors.as_json()})  # Provide detailed error messages
    else:
        form = ArticleForm(instance=article)

    context = {'add_form': form, 'article': article}
    return render(request, 'users/edit_article.html', context)


@login_required(login_url='users:login')
def published_articles(request):
    user = User.objects.get(id=request.user.id)
    article_list = Article.objects.filter(owner=user, is_draft=False).order_by('-add_date')
    paginator = Paginator(article_list, 6)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj': page_obj}
    return render(request, 'users/published_articles.html', context)


@login_required(login_url='users:login')
def draft_list(request):
    user = User.objects.get(id=request.user.id)
    drafts = Article.objects.filter(owner=user, is_draft=True).order_by('-add_date')
    paginator = Paginator(drafts, 6)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj': page_obj}
    return render(request, 'users/draft_list.html', context)


@login_required(login_url='users:login')
def delete_article(request, article_id):
    article = get_object_or_404(Article, id=article_id, owner=request.user)
    if request.method == 'POST':
        article.delete()
        messages.success(request, 'Chosen article was deleted successfully.')
        return redirect('blog:draft_list')  # 删除成功后重定向到草稿列表页面
    context = {'article': article}
    return render(request, 'users/delete_article.html', context)


@login_required(login_url='users:login')
def delete_comment(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id, user=request.user)
    if request.method == 'POST':
        comment.delete()
        messages.success(request, 'Chosen comment was deleted successfully.')
        return redirect('blog:comment_list')  # 删除成功后重定向到草稿列表页面
    context = {'comment': comment}
    return render(request, 'users/delete_comment.html', context)


@login_required(login_url='users:login')
def comment_list(request):
    comments = Comment.objects.filter(user=request.user)
    # if request.method == 'POST':
    #     comment.delete()
    #     messages.success(request, 'Chosen comment was deleted successfully.')
    #     return redirect('blog:comment_list')  # 删除成功后重定向到草稿列表页面
    paginator = Paginator(comments, 6)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {'page_obj': page_obj}
    return render(request, 'users/comment_list.html', context)


@login_required(login_url='users:login')
def get_comment_replies(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    replies = comment.replies.all()  # 获取所有回复
    reply_data = []

    # 构造回复数据
    for reply in replies:
        reply_data.append({
            'user': reply.user.username,
            'content': reply.content,
            'add_date': reply.add_date.strftime('%Y-%m-%d %H:%M'),
        })

    return JsonResponse({'replies': reply_data})

mysite/blog/templates/blog/archives_list.html
{% extends 'blog/base.html' %}
{% block title %} {{ year }} {{month}}'s archives{% endblock %}
{% block archives %}

<div class="box">
    Monthly archive: {{year}} {{month}}
    <div class="tags has-addons is-pulled-right">
    <span class="tag">altogether:</span>
    <span class="tag is-primary">{{article_list.count}} items</span>
</div>
</div>

{% endblock %}

mysite/blog/templates/blog/comment_template.html
{% load static %}
<style>
    /* 基本评论样式 */
    .comment, .reply {
        margin-bottom: 10px;
        display: flex;
        align-items: flex-start; /* 头像和内容对齐 */
    }

    /* 评论和回复内容容器 */
    .comment-content, .reply-content {
        margin-left: 10px; /* 内容与头像的间距 */
        flex: 1; /* 内容区域占据剩余空间 */
    }

    /* 回复的容器，控制所有级别的缩进 */
    .media-container {
        padding-left: 20px; /* 统一的缩进 */
    }

    /* 回复表单样式 */
    .reply-form {
        margin-top: 10px;
        display: none; /* 初始隐藏 */
    }

    /* 评论头部样式 */
    .comment-header, .reply-header {
        display: flex;
        align-items: center; /* 头像和用户名在同一行 */
    }

    /* 评论页脚样式 */
    .comment-footer, .reply-footer {
        display: flex;
        align-items: center;
    }

    /* 评论点赞计数样式 */
    .like-count {
        vertical-align: bottom;
        margin-left: 5px;
    }

    /* 头像样式 */
    .media-left .image {
        border-radius: 50%; /* 使头像圆形 */
        overflow: hidden; /* 隐藏溢出的部分 */
    }

    .comment .media-left .image {
        width: 48px; /* 主评论头像宽度 */
        height: 48px; /* 主评论头像高度 */
    }

    .reply .media-left .image {
        width: 32px; /* 回复头像宽度 */
        height: 32px; /* 回复头像高度 */
    }

    .media-left .image img {
        width: 100%; /* 使图片填满容器 */
        height: auto; /* 保持图片纵横比 */
        display: block; /* 去除图片底部的空白 */
    }

</style>

<!-- 主评论或回复 -->
<article class="media {% if comment.parent %}reply{% else %}comment{% endif %}">
    <div class="media-left">
        <a href="{% url 'users:other_user_profile' comment.user.username %}">
        <figure class="image">
            {% if comment.user.userprofile.image %}
                <img class="is-rounded" src="{{ MEDIA_URL }}{{ comment.user.userprofile.image.url }}" alt="User Avatar">
            {% else %}
                <img class="is-rounded" src="{% static 'users/images/avatar.png' %}" alt="Default Avatar">
            {% endif %}
        </figure>
        </a>

    </div>
    <div class="media-content comment-content">
        <div class="comment-header">
            <a href="{% url 'users:other_user_profile' comment.user.username %}" style="color:#61666D">
                <strong>{{ comment.user }}</strong>
            </a>            <!-- 显示父评论（或父回复） -->
        {% if comment.parent %}
            <div class="parent-comment" style="margin-left: 10px; solid #ddd;">
                <p>replies<a href="{% url 'users:other_user_profile' comment.parent.user.username %}"> @{{ comment.parent.user }}</a>:</p>
            </div>
            <p style="margin-left:5px">{{ comment.content|safe|linebreaks }}</p>
        {% endif %}
        </div>
        {% if not comment.parent %}
                <p>{{ comment.content|safe|linebreaks }}</p>
        {% endif %}
        <div class="comment-footer">
            <small style="color: #a0a0a0;">{{ comment.add_date }}</small>
            <nav class="level is-mobile">
                <a class="level-item" aria-label="reply">
                    <span class="icon is-small">
                        <i class="fas fa-reply" aria-hidden="true"></i>
                    </span>
                </a>
                <a class="level-item reply-button" aria-label="reply" data-id="comment-{{ comment.id }}">
                    <span class="icon is-small">
                        <i class="fas fa-retweet" aria-hidden="true">
                            <img src="{% static 'blog/images/reply.png' %}" style="margin-top:5px">
                        </i>
                    </span>
                </a>
                <a class="level-item" aria-label="like">
                    <span class="icon is-small">
                        <i class="fas fa-heart" aria-hidden="true">
                            <img src="{% static 'blog/images/like.png' %}" style="margin-top:3px">
                        </i>
                    </span>
                </a>
                {% if comment.likes %}
                    <span class="like-count">{{ comment.likes }}</span>
                {% endif %}
            </nav>
        </div>
    </div>
</article>

<!-- 回复表单，使用唯一的ID -->
<div class="reply-form" id="reply-form-comment-{{ comment.id }}">
    <form method="post">
        {% csrf_token %}
        <input type="hidden" name="parent_id" value="{{ comment.id }}">
        <div class="field">
            <div class="control">
                <textarea name="content" class="textarea" placeholder="Reply to @{{ comment.user.username }}"></textarea>
            </div>
        </div>
        <div class="field is-grouped">
            <div class="control" style="margin-left: auto;">
                <button class="button is-link" type="submit">Reply</button>
            </div>
        </div>
    </form>
</div>

<!-- 渲染子回复 -->
{% if comment.replies.all %}
    <div class="media-container">
        {% for reply in comment.replies.all %}
            {% include 'blog/comment_template.html' with comment=reply %}
        {% endfor %}
    </div>
{% endif %}

mysite/blog/templates/blog/detail.html
{% extends 'blog/base.html' %}
{% load static %}
{% block page-content %}
<div class="box">
    <h1 class="is-size-5 has-text-weight-bold">
        <a>{{ article.title }}</a>
    </h1>
    <div class="is-size-7 has-text-grey-light pt-1 pb-1">
        <span class="mr-6">Author: {{ article.owner }}</span>
        <span> Publish Date: {{ article.add_date }}</span>
    </div>
    <div class="content">
        {{ article.content|safe }}
    </div>
</div>

{% if messages %}
    <div class="messages" style="margin-bottom:10px">
        {% for message in messages %}
            <article class="message is-danger">
                <div class="message-header">
                    <p>Message Box</p>
                    <button class="delete" aria-label="delete"></button>
                </div>
                <div class="message-body">
                    {{ message }}
                </div>
            </article>
        {% endfor %}
    </div>
{% endif %}

<form method="post">
    {% csrf_token %}
    <div class="field">
        <div class="control">
            {{ form.content }}
        </div>
    </div>
    <div class="field is-grouped">
        <div class="control" style="margin-left: auto;">
            <button class="button is-link" type="submit">Publish</button>
        </div>
    </div>
</form>
<br/>

{% if user.is_authenticated %}
<div class="box">
    {% for comment in comments %}
        {% include 'blog/comment_template.html' with comment=comment %}
    {% endfor %}
</div>
{% else %}
<div class="box">
    <div class="level">
        <div class="level-left">
            After login can view all comments.
        </div>
    </div>
</div>
{% endif %}

<div class="box">
    <div class="level">
        <div class="level-left">
            {% if prev_article %}
                <span>Last Article:</span>
                <a href="{% url 'blog:article_detail' prev_article.id %}" class="level-item">{{ prev_article.title }}</a>
            {% else %}
                <span class="has-text-danger-dark is-size-7">Not exist last one</span>
            {% endif %}
        </div>
        <div class="level-right">
            {% if next_article %}
                <span>Next Article:</span>
                <a href="{% url 'blog:article_detail' next_article.id %}" class="level-item">{{ next_article.title }}</a>
            {% else %}
                <span class="has-text-danger-dark is-size-7">Already last one</span>
            {% endif %}
        </div>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        // 获取textarea元素
        const textarea = document.querySelector('textarea');
        // 获取所有删除按钮
        const deleteButtons = document.querySelectorAll('.message .delete');
        // 获取所有的回复按钮
        const replyButtons = document.querySelectorAll('.reply-button');
        // 获取所有的回复表单
        const replyForms = document.querySelectorAll('.reply-form');

        if (textarea) {
            // 定义一个函数来调整textarea的高度
            function autoResizeTextarea() {
                // 先将高度设为auto，以便获取正确的scrollHeight
                textarea.style.height = 'auto';
                // 根据内容的scrollHeight设置新的高度
                textarea.style.height = (textarea.scrollHeight) + 'px';
            }

            // 监听input事件来动态调整高度
            textarea.addEventListener('input', autoResizeTextarea);

            // 初始化textarea高度，适应初始内容
            autoResizeTextarea();
        }

        // 为每个删除按钮添加点击事件监听器
        deleteButtons.forEach(button => {
            button.addEventListener('click', function() {
                // 找到当前按钮所在的消息框
                const message = this.closest('.message');
                // 隐藏消息框
                if (message) {
                    message.style.display = 'none';
                }
            });
        });

        // 为每个回复按钮添加点击事件监听器
        replyButtons.forEach((button, index) => {
            button.addEventListener('click', function() {
                const replyForm = replyForms[index];
                // 切换显示/隐藏回复表单
                if (replyForm.style.display === 'none' || replyForm.style.display === '') {
                    replyForm.style.display = 'block';
                } else {
                    replyForm.style.display = 'none';
                }
            });
        });
    });
</script>

{% endblock %}

mysite/blog/templates/blog/index.html
{% extends 'blog/base.html' %}

mysite/blog/templates/blog/list.html
{% extends 'blog/base.html' %}